C104 rest ful
SudhamaniRM/Twitter_Project pull request #1
Opened 2021-10-29 08:33 UTC by SudhamaniRM

New files added

2021-11-01 15:48 UTC, SupriyaPamulapati approved these changes

2021-11-02 02:54 UTC, Kgaur624 approved these changes
I review your code 
proper indentation
Naming Convention is good 
whole code is distributed into the class
your code is working fine

2021-11-02 03:24 UTC, raj8789 approved these changes
your code i reviewed it is good to go

2021-11-02 03:50 UTC, SudhamaniRM commented on src/main/java/com/Twitter_Project/TwitterRunner.java
> +        System.out.println("Running.......");
It is for just testing

2021-11-02 04:20 UTC, SudhamaniRM commented on src/main/java/com/Twitter_Project/TwitterRunner.java
> +        System.out.println("Running.......");
Removed 👍🏼

2021-11-02 04:20 UTC, SudhamaniRM commented on src/main/java/com/Twitter_Project/TwitterResources.java
> +    public String[] getTimeline() throws TwitterException {
Added try and catch block

2021-11-02 05:14 UTC, anasuya1117 requested changes

2021-11-02 05:14 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/MyTweetClass.java
> +            Status statuses =twitter.updateStatus(msg);
Why `statuses`,Its not plural ryt ? make the variable singular, i.e `status`

2021-11-02 05:14 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/Request.java
> +        this.msg=msg;
space before and after `=`

2021-11-02 05:14 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/MyTimelineClass.java
> +    public static String[] MyTimeline() throws TwitterException {
Wrong naming convention for function name, Java methods should be named using camel-cases and start with small letter, always.

2021-11-02 05:14 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/MyTweetClass.java
> +    public static void MyTweet(String msg) throws TwitterException {
Wrong naming convention for function name, Java methods should be named using camel-cases and start with small letter, always.

2021-11-02 05:14 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/TwitterResources.java
> +    public String[] getTimeline(){
Its should return `Response` like post API and u should handle the Exception in the same way.

2021-11-02 05:14 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/TwitterResources.java
> +    public String[] getTimeline(){
This api should return `Response` object same as post API, and exceptions should be handled in the same way

2021-11-02 05:14 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/TwitterResources.java
> +                MyTweetClass.MyTweet(msg);
can we add the return statement here itself ? after line no 31 ?

2021-11-02 10:38 UTC, anasuya1117 requested changes

2021-11-02 10:38 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/MyTweetClass.java
> +          twitter.updateStatus(msg);
in case of wrong auth details , it will not catch the error, check the response of `twitter.updateStatus` and return something from this function. Otherwise in case of unsuccessful tweet also ur api will give 200 status

2021-11-02 10:38 UTC, anasuya1117 commented on src/main/java/com/Twitter_Project/TwitterResources.java
> +        str = MyTimelineClass.myTimeline();
Combine these into a single line,
```
String str = MyTimelineClass.myTimeline();
```

2021-11-03 08:12 UTC, anasuya1117 approved these changes

2021-11-03 08:51 UTC, merged